# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ggang

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_de979d2124d54e6e8257595d568cc7c1 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_51085af04ecf41808b5873ce8fe007cf }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_de979d2124d54e6e8257595d568cc7c1 }}/kangbyeonggyu/footballmoaback:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ggang'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7951c2fcd424472996e2f77b932a4b6f }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_de979d2124d54e6e8257595d568cc7c1 }}/kangbyeonggyu/footballmoaback:${{ github.sha }}'